# Generated by Django 4.1.4 on 2022-12-12 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='image',
            field=models.ImageField(default='image', upload_to='Images'),
            preserve_default=False,
        ),
    ]
