# Generated by Django 4.1.5 on 2023-01-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(default='image/None/noimg.jpg', upload_to='image/'),
        ),
    ]
